### ISSUE TITLE
Error just after typed my password

### ISSUE THREAD

**Issue by Naografix** [andrea-varesio/instracker#1]
Hey,

I'm trying your script but I got an error when I want to log in (just after the password)

```
Enter your password:
Traceback (most recent call last):
  File "C:\Users\Naografix\Downloads\instracker-main\instracker-main\instracker.py", line 244, in <module>
    main()
  File "C:\Users\Naografix\Downloads\instracker-main\instracker-main\instracker.py", line 229, in main
    instagram, account = get_credentials()
  File "C:\Users\Naografix\Downloads\instracker-main\instracker-main\instracker.py", line 104, in get_credentials
    instagram.login(force=False,two_step_verificator=False)
  File "C:\Users\Naografix\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\igramscraper\instagram.py", line 1320, in login
    and response.json()['message'] == 'checkpoint_required'
  File "C:\Users\Naografix\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Tried to change the 2FA but still nothing.

Thank you

**Comment by andrea-varesio** [comment]
Since the [instagram_scraper](https://github.com/realsirjoe/instagram-scraper) dependency is no longer being developed, this repository will be archived.
